### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by jonaisahhh** [jonaisahhh/ETI-Assignment#3]
- [ ] Test Cases for Project

**Comment by jonaisahhh** [comment]
@Arm57ar @ShahrulNizamBR - Please submit the test cases by today so that I may review it. Thank you

**Comment by Arm57ar** [comment]
Hi.Sorry for late response. We have created the test case for displaying Menu,  Read & Load Maze from selected file and play Maze from selected file. - Shahrul & Amsyar
[Test_Case_Assignment.docx](https://github.com/jonaisahhh/ETI-Assignment/files/4142953/Test_Case_Assignment.docx)

**Comment by jonaisahhh** [comment]
@Arm57ar @ShahrulNizamBR - Thank you! 

@kazooie20 - Please take note that test cases from QA are done.
