### ISSUE TITLE
Unit Test cases for feature 1, 4 & 5

### ISSUE THREAD

**Issue by rayner77** [jonaisahhh/ETI-Assignment#4]
After you are done, please issue it as 'waiting for approval' for technical lead to look through and approve. Thankss and have fun writing tests. Any queries whatsapp me

**Comment by jonaisahhh** [comment]
@reynaldicheok - Please upload the unit test cases by today as stated on the Project & Development Timeline. Thank you

**Comment by reynaldicheok** [comment]
Committed the unit test cases on the repository.

**Comment by jonaisahhh** [comment]
@kazooie20 - Please review the unit test cases & do let me know if there are any issues. Thank you

**Comment by rayner77** [comment]
Unit test cases approved
