### ISSUE TITLE
Unit test cases for feature 3

### ISSUE THREAD

**Issue by rayner77** [jonaisahhh/ETI-Assignment#5]
After you are done, please issue it as 'waiting for approval' for technical lead to look through and approve. Thankss and have fun writing tests. Any queries whatsapp me

**Comment by Arm57ar** [comment]
I have created the new test case for the view Maze. Currently waiting for approval from the QA and technical Lead.
[Test_Case_View_Maze.docx](https://github.com/jonaisahhh/ETI-Assignment/files/4142594/Test_Case_View_Maze.docx)

**Comment by jonaisahhh** [comment]
@Arm57ar - I have looked into the Test Cases.

@kazooie20 - Please take a look on the Unit Test Cases for Feature 3

**Comment by Arm57ar** [comment]
Hi, Sorry. I have updated the latest test case for Feature 3 on load the Maze
[Figure3_load_the_Maze.docx](https://github.com/jonaisahhh/ETI-Assignment/files/4143036/Figure3_load_the_Maze.docx)

**Comment by ShahrulNizamBR** [comment]
@Arm57ar  I have taken a look at the test case for feature 3. I will compile the case with the other features. Thank you.

**Comment by Arm57ar** [comment]
Noted @ShahrulNizamBR

**Comment by jonaisahhh** [comment]
@ShahrulNizamBR @Arm57ar - Thank you!
