### ISSUE TITLE
QA Test Cases

### ISSUE THREAD

**Issue by ShahrulNizamBR** [jonaisahhh/ETI-Assignment#7]
Hi. I have just compiled all the test cases for all the features here. Please refer to the file attached and let me know if there are any problems/changes to be made.

Thank you.
[Test_Case_Assignment.docx](https://github.com/jonaisahhh/ETI-Assignment/files/4143500/Test_Case_Assignment.docx)

**Comment by Arm57ar** [comment]
Thanks @ShahrulNizamBR

**Comment by jonaisahhh** [comment]
@ShahrulNizamBR - Thank you

@kazooie20 - Please take note that QA Test Cases have been compiled
